name: health_balance
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation:
  flutter_svg:


dev_dependencies:
  flutter_test:
    sdk: flutter

  equatable:
  hive:
  hive_generator:
  build_runner:
  freezed:
  path_provider:
  formz:
  flutter_bloc:
  intl:


flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
